module.exports = [
  {name: "Aceite de soja"},
  {name: "Aceite de maíz"},
  {name: "Aceite de oliva"},
  {name: "Aceite de trufa"},
  {name: "Nata o crema de leche"},
  {name: "Yogur"},
  {name: "Leche"},
  {name: "Helado"},
  {name: "Queso"},
  {name: "Cuajada"},
  {name: "Mantequilla"},
  {name: "Setas"},
  {name: "Hongos"},
  {name: "Coles"},
  {name: "Legumbres"},
  {name: "Alubias"},
  {name: "Garbanzos"},
  {name: "Lentejas"},
  {name: "Soja"},
  {name: "Pimientas"},
  {name: "Patata"},
  {name: "Raíces y tubérculos"},
  {name: "Lechugas"},
  {name: "Acelga"},
  {name: "Alcachofa"},
  {name: "Batata"},
  {name: "Berenjena"},
  {name: "Berro"},
  {name: "Brócoli"},
  {name: "Brecol"},
  {name: "Calabacín"},
  {name: "Calabaza"},
  {name: "Cardo"},
  {name: "Cebolla"},
  {name: "Cebolla caramelizada"},
  {name: "Cebolleta"},
  {name: "Coles de Bruselas"},
  {name: "Coliflor"},
  {name: "Endivia"},
  {name: "Tomate"},
  {name: "Zanahoria"},
  {name: "Escarola"},
  {name: "Espárrago"},
  {name: "Espinaca"},
  {name: "Guisante"},
  {name: "Habas"},
  {name: "Habichuelas"},
  {name: "Hinojo"},
  {name: "Judías"},
  {name: "Maíz"},
  {name: "Palmito"},
  {name: "Pepino"},
  {name: "Pimiento"},
  {name: "Puerro"},
  {name: "Remolacha"},
  {name: "Albaricoque"},
  {name: "Caquis"},
  {name: "Aguacate"},
  {name: "Cereza"},
  {name: "Mango"},
  {name: "Melocotones"},
  {name: "Nectarina"},
  {name: "Ciruela"},
  {name: "Fruta del bosque"},
  {name: "Frutos secos"},
  {name: "Membrillo"},
  {name: "Peras"},
  {name: "Manzanas"},
  {name: "Uvas"},
  {name: "Fruta seca"},
  {name: "Frambuesa"},
  {name: "Fresa"},
  {name: "Granada"},
  {name: "Higos"},
  {name: "Kiwi"},
  {name: "Limón"},
  {name: "Mandarina"},
  {name: "Melón"},
  {name: "Naranja"},
  {name: "Piña"},
  {name: "Plátano"},
  {name: "Pomelo"},
  {name: "Sandía"},
  {name: "Cereales"},
  {name: "Harinas"},
  {name: "Panes"},
  {name: "Arroz"},
  {name: "Pasta"},
  {name: "Atún"},
  {name: "Anchoa"},
  {name: "Bacalao"},
  {name: "Besugo"},
  {name: "Bonito"},
  {name: "Boquerón"},
  {name: "Caballa"},
  {name: "Chicharro"},
  {name: "Corvina"},
  {name: "Dorada"},
  {name: "Lenguado"},
  {name: "Lubina"},
  {name: "Merluza"},
  {name: "Mero"},
  {name: "Palometa"},
  {name: "Pejerrey"},
  {name: "Rape"},
  {name: "Rodaballo"},
  {name: "Salmón"},
  {name: "Sardina"},
  {name: "Trucha"},
  {name: "Camarón"},
  {name: "Cigala"},
  {name: "Gamba"},
  {name: "Langostino"},
  {name: "Percebe"},
  {name: "Almeja"},
  {name: "Calamar"},
  {name: "Mejillón"},
  {name: "Ostra"},
  {name: "Pulpo"},
  {name: "Sepia"},
  {name: "Vieira"},
  {name: "Cordero"},
  {name: "Ovejas"},
  {name: "Ternera"},
  {name: "Buey"},
  {name: "Caballo"},
  {name: "Cabra"},
  {name: "Cerdo"},
  {name: "Vaca"},
  {name: "Avestruz"},
  {name: "Paloma"},
  {name: "Perdiz"},
  {name: "Patos"},
  {name: "Pavos"},
  {name: "Ocas"},
  {name: "Gallinas"},
  {name: "Pollo"},
  {name: "capones"},
  {name: "huevos"},
  {name: "Clara "},
  {name: "yema"},
  {name: "Bison"},
  {name: "Conejo"},
  {name: "Liebre"},
  {name: "Oso"},
  {name: "Ciervo"},
  {name: "Jabalí"},
  {name: "Faisanes"},
  {name: "Ancas de rana"},
  {name: "Caracoles"},
  {name: "Cervezas"},
  {name: "Sidras"},
  {name: "Licores"},
  {name: "Vino blanco"},
  {name: "Vino caliente"},
  {name: "Vino tinto"},
  {name: "Vino rosado"},
  {name: "Vino dulce"},
  {name: "Whisky"},
  {name: "Cafés"},
  {name: "Cola"},
  {name: "Agua"},
  {name: "Agua mineral"},
  {name: "Agua gaseosa"},
  {name: "Zumo"},
  {name: "Tés"},
  {name: "Horchata"},
  {name: "Cerveza sin alcoh"}
]